Repository kat-kelly/Fairy-and-Giant, pull requests merged in 2021-09, with the labels that each got.

#42 Tutorial area trigger update
  Content/ThirdPersonBP/Objects/Tutorial/EBase.uasset
  Content/ThirdPersonBP/Objects/Tutorial/EGreen.uasset
  Content/ThirdPersonBP/Objects/Tutorial/TutorialAreaTrigger.uasset
Labels: enhancement

#53 Destroy animation bugfixes
  Content/ThirdPerson/Characters/Stomp4UE4.uasset
  Content/ThirdPerson/Characters/Stomp4UE4_Montage.uasset
  Content/ThirdPersonBP/Objects/DestroyableObject_BP_2.uasset
Labels: bug

#70 NPC Rabbit Setup
  Content/AnimalVarietyPack/Rabbit/BPA_Rabbit.uasset
  Content/AnimalVarietyPack/Rabbit/BSP_Rabbit.uasset
  Content/AnimalVarietyPack/Rabbit/Main.uasset
  Content/AnimalVarietyPack/Rabbit/README.txt
  Content/AnimalVarietyPack/Rabbit/Rabbit.uasset
  Content/AnimalVarietyPack/Rabbit/Rabbit_Anim.uasset
  Content/AnimalVarietyPack/Rabbit/Rabbit_Anim_Slow.uasset
  Content/AnimalVarietyPack/Rabbit/Rabbit_Idle.uasset
  Content/AnimalVarietyPack/Rabbit/Rabbit_PhysicsAsset.uasset
  Content/AnimalVarietyPack/Rabbit/Rabbit_Skeleton.uasset
  Content/ThirdPersonBP/Blueprints/NPC/AI_Controller_Bird.uasset
  Content/ThirdPersonBP/Blueprints/NPC/AI_Controller_Rabbit.uasset
  Content/ThirdPersonBP/Blueprints/NPC/Bird/Ch_Bird.uasset
  Content/ThirdPersonBP/Blueprints/NPC/BirdStates.uasset
  Content/ThirdPersonBP/Blueprints/NPC/Rabbit/Ch_Rabbit.uasset
Labels: addition

#84 Lava Terrain Ambient lightsource
  Content/ThirdPerson/Environmental/Lava/M_Lava_Flowing.uasset
  Content/ThirdPerson/Environmental/Lava/flipbooklava.uasset
  Content/ThirdPerson/Environmental/Lava/flipbooklava_Mat.uasset
  Content/ThirdPersonBP/Objects/Terrain_Lava.uasset
Labels: enhancement

#87 Draft Quicksand
  Content/ThirdPersonBP/Blueprints/ThirdPersonCharacterFairy.uasset
  Content/ThirdPersonBP/Blueprints/ThirdPersonCharacterGiant.uasset
  Content/ThirdPersonBP/Objects/QuickSand.uasset
Labels: addition, fairy, giant

#88 Completed Quicksand!
  Content/ThirdPersonBP/Blueprints/ThirdPersonCharacterGiant.uasset
  Content/ThirdPersonBP/Objects/QuickSand.uasset
Labels: addition, fairy, giant

#94 Component Updates
  Content/ThirdPersonBP/Blueprints/ThirdPersonCharacterFairy.uasset
  Content/ThirdPersonBP/Blueprints/ThirdPersonCharacterGiant.uasset
  Content/ThirdPersonBP/Blueprints/charSwapComponent.uasset
  Content/ThirdPersonBP/Objects/Components/Giant_Interact_Component.uasset
  Content/ThirdPersonBP/Objects/Components/Push_Component.uasset
  Content/ThirdPersonBP/Objects/DestroyableObject_BP_2.uasset
  Content/ThirdPersonBP/Objects/MovingObjects.uasset
  Content/ThirdPersonBP/Objects/PushableObject_BP.uasset
Labels: bug

#95 Enchantment Component
  Content/ThirdPersonBP/Blueprints/ThirdPersonCharacterFairy.uasset
  Content/ThirdPersonBP/Blueprints/charSwapComponent.uasset
  Content/ThirdPersonBP/Objects/Components/Enchant_Component.uasset
  Content/ThirdPersonBP/Objects/MovingObjects.uasset
Labels: bug
